# Use an official Node.js runtime as a parent image
FROM node:14.15.1-alpine3.10

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the application
RUN npm run build --prod

# Set the command to run when the container starts
CMD ["npm", "start"]
